"""add unit field to order table

Revision ID: 3e3292521012
Revises: 6320797197b8
Create Date: 2025-06-10 02:02:08.054061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3292521012'
down_revision: Union[str, None] = '6320797197b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('unit', sa.Enum('KRW', 'USD', name='unitenum'), nullable=False, comment='화폐 단위 (KRW, USD)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'unit')
    # ### end Alembic commands ###
